name: Autorelease
on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:
    inputs:
      git-ref:
        description: Force release  
        required: false
jobs:
  FetchMap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.head_ref}}
      
      - run: "./oui_update.sh"
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Daily autoupdate
  
  Release:
    runs-on: ubuntu-latest
    needs: [FetchMap]
    
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
      - name: Get next version
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1.0"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.semvers.outputs.patch }}
          release_name: ${{ steps.semvers.outputs.patch }}
          draft: false
          prerelease: false
