name: Autorelease
on: repository_dispatch
jobs:
  FetchMap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.head_ref}}
      
      - run: "./oui_update.sh"
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Daily autoupdate
  
  Release:
    runs-on: ubuntu-latest
    needs: [FetchMap]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false
